import PptxGenJS from 'pptxgenjs';
import type { ContentPlan, ContentSlide, TemplateAnalysis, SlideData, SlideContent, ColorPalette, FontSpec } from '@pitchdeck/shared-types';

/**
 * Slide Builder Service
 *
 * Programmatically assembles PowerPoint slides by manually placing
 * every visual element: shapes, text boxes, tables, charts, lines.
 *
 * Uses PptxGenJS as a low-level API — we control every pixel.
 * No high-level "generate a presentation" abstraction.
 *
 * The builder reads template analysis (extracted layouts, colours, fonts)
 * and content plan (slide specifications) to produce a .pptx file
 * that matches the reference template's visual identity.
 */
export class SlideBuilderService {

  /**
   * Build a complete .pptx from content plan + template analysis.
   * Each slide is constructed element by element.
   */
  async buildPresentation(
    contentPlan: ContentPlan,
    templateAnalysis: TemplateAnalysis,
  ): Promise<{ buffer: Buffer; slidesData: SlideData[] }> {
    const pptx = new PptxGenJS();
    const palette = templateAnalysis.color_palette;
    const fonts = templateAnalysis.fonts;

    // Configure presentation
    pptx.layout = 'LAYOUT_WIDE'; // 13.33" x 7.5"
    pptx.author = 'AI Pitch Deck Builder';
    pptx.company = 'Generated by AI';
    pptx.subject = contentPlan.title;

    // Define master slide
    pptx.defineSlideMaster({
      title: 'PB_MASTER',
      background: { color: this.hex(palette.background) },
      objects: [
        // Top accent bar
        { rect: { x: 0, y: 0, w: '100%', h: 0.04, fill: { color: this.hex(palette.primary) } } },
        // Bottom bar with slide number
        { rect: { x: 0, y: 7.2, w: '100%', h: 0.01, fill: { color: this.hex(palette.primary) } } },
        // Footer text
        { text: {
          text: 'CONFIDENTIAL',
          options: { x: 0.5, y: 7.05, w: 2, h: 0.3, fontSize: 7, fontFace: this.titleFont(fonts), color: '999999', italic: true },
        }},
        // Slide number placeholder
        { text: {
          text: '',
          options: { x: 9.2, y: 7.05, w: 0.6, h: 0.3, fontSize: 7, fontFace: this.bodyFont(fonts), color: '999999', align: 'right' },
        }},
      ],
    });

    const slidesData: SlideData[] = [];

    for (const slidePlan of contentPlan.slides) {
      const slideContents: SlideContent[] = [];

      // Title slide uses custom layout (no master)
      if (slidePlan.layout === 'Title Slide') {
        const slide = pptx.addSlide();
        this.buildTitleSlide(slide, slidePlan, palette, fonts, slideContents);
        this.addSlideNotes(slide, slidePlan);
      } else if (slidePlan.layout === 'Section Header') {
        const slide = pptx.addSlide();
        this.buildSectionHeader(slide, slidePlan, palette, fonts, slideContents);
        this.addSlideNotes(slide, slidePlan);
      } else {
        // All other layouts use the master
        const slide = pptx.addSlide({ masterName: 'PB_MASTER' });
        this.addSlideNumber(slide, slidePlan.index + 1, fonts);

        switch (slidePlan.layout) {
          case 'Financial Table':
          case 'Comparison Table':
            this.buildTableSlide(slide, slidePlan, palette, fonts, slideContents);
            break;
          case 'Key Metrics':
            this.buildMetricsSlide(slide, slidePlan, palette, fonts, slideContents);
            break;
          case 'Two Column':
            this.buildTwoColumnSlide(slide, slidePlan, palette, fonts, slideContents);
            break;
          case 'Chart Slide':
            this.buildChartSlide(slide, slidePlan, palette, fonts, slideContents);
            break;
          case 'Executive Summary':
            this.buildExecutiveSummary(slide, slidePlan, palette, fonts, slideContents);
            break;
          default:
            this.buildContentSlide(slide, slidePlan, palette, fonts, slideContents);
            break;
        }
        this.addSlideNotes(slide, slidePlan);
      }

      slidesData.push({
        index: slidePlan.index,
        title: slidePlan.title,
        layout: slidePlan.layout,
        content: slideContents,
        notes: slidePlan.talking_points?.join('\n'),
      });
    }

    const output = await pptx.write({ outputType: 'nodebuffer' }) as Buffer;
    return { buffer: output, slidesData };
  }

  // ── Title Slide ──
  // Full custom layout: accent bars, centered title, subtitle, date, confidential notice.

  private buildTitleSlide(
    slide: any, plan: ContentSlide, palette: ColorPalette, fonts: FontSpec[], contents: SlideContent[],
  ) {
    const bg = this.hex(palette.background);
    slide.background = { color: bg };

    // Top accent bar (thicker on title)
    slide.addShape('rect', { x: 0, y: 0, w: '100%', h: 0.12, fill: { color: this.hex(palette.primary) } });

    // Left accent stripe
    slide.addShape('rect', { x: 0, y: 0, w: 0.06, h: '100%', fill: { color: this.hex(palette.primary) } });

    // Title text
    const titleText = this.getBlockContent(plan, 'heading') || plan.title;
    slide.addText(titleText, {
      x: 0.8, y: 1.8, w: 8.5, h: 1.8,
      fontSize: 36, fontFace: this.titleFont(fonts), bold: true,
      color: this.hex(palette.primary),
      align: 'left', valign: 'bottom',
      lineSpacingMultiple: 1.1,
    });
    contents.push({ type: 'text', placeholder: 'title', value: titleText });

    // Horizontal divider line
    slide.addShape('line', {
      x: 0.8, y: 3.8, w: 3.5, h: 0,
      line: { color: this.hex(palette.accent), width: 2 },
    });

    // Subtitle / description
    const paragraphs = this.getAllBlockContent(plan, 'paragraph');
    if (paragraphs.length > 0) {
      slide.addText(paragraphs[0], {
        x: 0.8, y: 4.1, w: 8.5, h: 0.8,
        fontSize: 18, fontFace: this.bodyFont(fonts),
        color: this.hex(palette.secondary),
        align: 'left',
      });
      contents.push({ type: 'text', placeholder: 'subtitle', value: paragraphs[0] });
    }

    // Date
    if (paragraphs.length > 1) {
      slide.addText(paragraphs[1], {
        x: 0.8, y: 5.3, w: 4.0, h: 0.5,
        fontSize: 12, fontFace: this.bodyFont(fonts),
        color: '666666',
      });
    } else {
      slide.addText(new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' }), {
        x: 0.8, y: 5.3, w: 4.0, h: 0.5,
        fontSize: 12, fontFace: this.bodyFont(fonts),
        color: '666666',
      });
    }

    // Confidential notice
    slide.addText('CONFIDENTIAL — FOR DISCUSSION PURPOSES ONLY', {
      x: 0.8, y: 6.4, w: 6.0, h: 0.3,
      fontSize: 8, fontFace: this.bodyFont(fonts),
      color: '999999', italic: true,
    });

    // Bottom accent bar
    slide.addShape('rect', { x: 0, y: 7.35, w: '100%', h: 0.15, fill: { color: this.hex(palette.primary) } });
  }

  // ── Section Header ──
  // Full-bleed primary colour background with white text.

  private buildSectionHeader(
    slide: any, plan: ContentSlide, palette: ColorPalette, fonts: FontSpec[], contents: SlideContent[],
  ) {
    slide.background = { color: this.hex(palette.primary) };

    // Decorative accent line
    slide.addShape('line', {
      x: 0.8, y: 3.0, w: 2.5, h: 0,
      line: { color: this.hex(palette.accent), width: 3 },
    });

    slide.addText(plan.title, {
      x: 0.8, y: 3.3, w: 8.5, h: 2.0,
      fontSize: 32, fontFace: this.titleFont(fonts), bold: true,
      color: 'FFFFFF', align: 'left', valign: 'top',
    });
    contents.push({ type: 'text', placeholder: 'title', value: plan.title });

    // Section number (subtle)
    slide.addText(String(plan.index + 1).padStart(2, '0'), {
      x: 0.8, y: 1.5, w: 2, h: 1.2,
      fontSize: 60, fontFace: this.titleFont(fonts), bold: true,
      color: 'FFFFFF', transparency: 70,
    });
  }

  // ── Content Slide ──
  // Standard layout: title bar + body content (bullets, paragraphs).

  private buildContentSlide(
    slide: any, plan: ContentSlide, palette: ColorPalette, fonts: FontSpec[], contents: SlideContent[],
  ) {
    // Slide title with underline
    this.addSlideTitle(slide, plan.title, palette, fonts);
    contents.push({ type: 'text', placeholder: 'title', value: plan.title });

    let yPos = 1.3;

    for (const block of (plan.content_blocks || [])) {
      if (block.type === 'heading') continue;

      if (block.type === 'bullet_list' && Array.isArray(block.content)) {
        const bulletRows = block.content.map((item: string) => ({
          text: item,
          options: {
            fontSize: 12, fontFace: this.bodyFont(fonts),
            color: this.hex(palette.text),
            bullet: { type: 'bullet', char: '●', indent: 18 },
            paraSpaceBefore: 2, paraSpaceAfter: 6,
          },
        }));

        const height = Math.min(block.content.length * 0.4 + 0.2, 5.5);
        slide.addText(bulletRows, {
          x: 0.5, y: yPos, w: 9.0, h: height,
          valign: 'top',
        });
        contents.push({ type: 'list', placeholder: 'body', value: block.content });
        yPos += height;
      } else if (block.type === 'paragraph') {
        const text = String(block.content);
        const lines = Math.ceil(text.length / 100);
        const height = Math.max(lines * 0.35, 0.5);

        slide.addText(text, {
          x: 0.5, y: yPos, w: 9.0, h: height,
          fontSize: 12, fontFace: this.bodyFont(fonts),
          color: this.hex(palette.text),
          valign: 'top', lineSpacingMultiple: 1.3,
        });
        contents.push({ type: 'text', placeholder: 'body', value: text });
        yPos += height + 0.15;
      } else if (block.type === 'metric') {
        // Inline metric card
        const label = block.content?.label || '';
        const value = block.content?.value || 'N/A';

        slide.addShape('roundRect', {
          x: 0.5, y: yPos, w: 2.8, h: 1.2,
          fill: { color: 'F8F9FA' }, rectRadius: 0.08,
          line: { color: 'E5E5E5', width: 0.5 },
        });
        slide.addText(value, {
          x: 0.5, y: yPos + 0.15, w: 2.8, h: 0.6,
          fontSize: 22, fontFace: this.titleFont(fonts), bold: true,
          color: this.hex(palette.primary), align: 'center',
        });
        slide.addText(label, {
          x: 0.5, y: yPos + 0.75, w: 2.8, h: 0.3,
          fontSize: 10, fontFace: this.bodyFont(fonts),
          color: '666666', align: 'center',
        });
        contents.push({ type: 'text', placeholder: 'metric', value: block.content });
        yPos += 1.4;
      }
    }
  }

  // ── Financial Table Slide ──
  // Professionally formatted table with header row styling, alternating rows, and borders.

  private buildTableSlide(
    slide: any, plan: ContentSlide, palette: ColorPalette, fonts: FontSpec[], contents: SlideContent[],
  ) {
    this.addSlideTitle(slide, plan.title, palette, fonts);
    contents.push({ type: 'text', placeholder: 'title', value: plan.title });

    const tableBlock = (plan.content_blocks || []).find(b => b.type === 'table');
    if (!tableBlock?.content) {
      // No table data — show placeholder text
      slide.addText('Financial data table', {
        x: 0.5, y: 1.5, w: 9.0, h: 4.5,
        fontSize: 14, fontFace: this.bodyFont(fonts),
        color: '999999', align: 'center', valign: 'middle',
      });
      return;
    }

    const { headers, rows } = tableBlock.content;
    const tableData: any[][] = [];
    const numCols = headers?.length || 2;

    // Header row — manually styled cells
    if (headers) {
      tableData.push(headers.map((h: string) => ({
        text: String(h),
        options: {
          bold: true, fontSize: 10, fontFace: this.bodyFont(fonts),
          color: 'FFFFFF',
          fill: { color: this.hex(palette.primary) },
          align: 'center', valign: 'middle',
          border: [
            { type: 'solid', pt: 0.5, color: this.hex(palette.primary) },
            { type: 'solid', pt: 0.5, color: this.hex(palette.primary) },
            { type: 'solid', pt: 1, color: this.hex(palette.accent) },
            { type: 'solid', pt: 0.5, color: this.hex(palette.primary) },
          ],
          margin: [4, 6, 4, 6],
        },
      })));
    }

    // Data rows — alternating background, right-aligned numbers
    for (let i = 0; i < (rows || []).length; i++) {
      const row = rows[i];
      const isEven = i % 2 === 0;
      const bgColor = isEven ? 'F5F7FA' : 'FFFFFF';

      tableData.push(row.map((cell: string, j: number) => {
        const isNumeric = j > 0 && /^[\$£€\-\d,.\s%xX]+$/.test(String(cell).trim());
        return {
          text: String(cell),
          options: {
            fontSize: 9, fontFace: this.bodyFont(fonts),
            color: this.hex(palette.text),
            fill: { color: bgColor },
            align: j === 0 ? 'left' : (isNumeric ? 'right' : 'center'),
            valign: 'middle',
            border: [
              { type: 'solid', pt: 0.3, color: 'E5E5E5' },
              { type: 'solid', pt: 0.3, color: 'E5E5E5' },
              { type: 'solid', pt: 0.3, color: 'E5E5E5' },
              { type: 'solid', pt: 0.3, color: 'E5E5E5' },
            ],
            margin: [3, 6, 3, 6],
          },
        };
      }));
    }

    if (tableData.length > 0) {
      const colWidths = Array(numCols).fill(9.0 / numCols);
      // First column (labels) gets more width
      if (numCols > 2) {
        colWidths[0] = 2.5;
        const remaining = (9.0 - 2.5) / (numCols - 1);
        for (let i = 1; i < numCols; i++) colWidths[i] = remaining;
      }

      slide.addTable(tableData, {
        x: 0.5, y: 1.3, w: 9.0,
        rowH: 0.35,
        colW: colWidths,
        border: { type: 'solid', pt: 0, color: 'FFFFFF' },
      });
      contents.push({ type: 'table', placeholder: 'table', value: tableBlock.content });
    }

    // Source attribution
    slide.addText('Source: Yahoo Finance, SEC EDGAR, Company Reports', {
      x: 0.5, y: 6.5, w: 9.0, h: 0.3,
      fontSize: 7, fontFace: this.bodyFont(fonts),
      color: '999999', italic: true,
    });
  }

  // ── Key Metrics Slide ──
  // Card-based layout with large metric values.

  private buildMetricsSlide(
    slide: any, plan: ContentSlide, palette: ColorPalette, fonts: FontSpec[], contents: SlideContent[],
  ) {
    this.addSlideTitle(slide, plan.title, palette, fonts);
    contents.push({ type: 'text', placeholder: 'title', value: plan.title });

    const metricBlocks = (plan.content_blocks || []).filter(b => b.type === 'metric');
    const count = Math.max(metricBlocks.length, 1);
    const maxCols = Math.min(count, 4);
    const cardGap = 0.25;
    const totalWidth = 9.0;
    const cardWidth = (totalWidth - (maxCols - 1) * cardGap) / maxCols;

    for (let i = 0; i < metricBlocks.length; i++) {
      const col = i % maxCols;
      const row = Math.floor(i / maxCols);
      const x = 0.5 + col * (cardWidth + cardGap);
      const y = 1.5 + row * 2.8;

      const block = metricBlocks[i];
      const label = block.content?.label || '';
      const value = block.content?.value || 'N/A';

      // Card shadow (offset rectangle)
      slide.addShape('roundRect', {
        x: x + 0.03, y: y + 0.03, w: cardWidth, h: 2.2,
        fill: { color: 'E0E0E0' }, rectRadius: 0.1,
      });

      // Card background
      slide.addShape('roundRect', {
        x, y, w: cardWidth, h: 2.2,
        fill: { color: 'FFFFFF' }, rectRadius: 0.1,
        line: { color: 'E5E5E5', width: 0.5 },
      });

      // Colour accent bar at top of card
      slide.addShape('rect', {
        x: x + 0.15, y: y + 0.15, w: cardWidth - 0.3, h: 0.04,
        fill: { color: this.hex(palette.primary) },
      });

      // Metric value
      slide.addText(value, {
        x, y: y + 0.4, w: cardWidth, h: 1.0,
        fontSize: 28, fontFace: this.titleFont(fonts), bold: true,
        color: this.hex(palette.primary),
        align: 'center', valign: 'middle',
      });

      // Metric label
      slide.addText(label, {
        x, y: y + 1.4, w: cardWidth, h: 0.5,
        fontSize: 11, fontFace: this.bodyFont(fonts),
        color: '666666',
        align: 'center', valign: 'top',
      });

      contents.push({ type: 'text', placeholder: `metric_${i}`, value: block.content });
    }
  }

  // ── Two Column Slide ──
  // Split layout with optional visual divider.

  private buildTwoColumnSlide(
    slide: any, plan: ContentSlide, palette: ColorPalette, fonts: FontSpec[], contents: SlideContent[],
  ) {
    this.addSlideTitle(slide, plan.title, palette, fonts);
    contents.push({ type: 'text', placeholder: 'title', value: plan.title });

    // Vertical divider
    slide.addShape('line', {
      x: 5.0, y: 1.3, w: 0, h: 5.0,
      line: { color: 'E5E5E5', width: 0.5 },
    });

    const nonHeading = (plan.content_blocks || []).filter(b => b.type !== 'heading');

    if (nonHeading.length > 0 && nonHeading[0].type === 'bullet_list' && Array.isArray(nonHeading[0].content)) {
      const items = nonHeading[0].content;
      const half = Math.ceil(items.length / 2);
      const leftItems = items.slice(0, half);
      const rightItems = items.slice(half);

      const formatBullets = (list: string[]) => list.map((item: string) => ({
        text: item,
        options: {
          fontSize: 11, fontFace: this.bodyFont(fonts),
          color: this.hex(palette.text),
          bullet: { type: 'bullet', char: '●', indent: 14 },
          paraSpaceBefore: 2, paraSpaceAfter: 5,
        },
      }));

      if (leftItems.length) {
        slide.addText(formatBullets(leftItems), { x: 0.5, y: 1.3, w: 4.3, h: 5.0, valign: 'top' });
      }
      if (rightItems.length) {
        slide.addText(formatBullets(rightItems), { x: 5.2, y: 1.3, w: 4.3, h: 5.0, valign: 'top' });
      }
      contents.push({ type: 'list', placeholder: 'body', value: items });
    } else {
      // Two separate content blocks
      for (let i = 0; i < Math.min(nonHeading.length, 2); i++) {
        const block = nonHeading[i];
        const x = i === 0 ? 0.5 : 5.2;
        const text = typeof block.content === 'string' ? block.content : JSON.stringify(block.content);
        slide.addText(text, {
          x, y: 1.3, w: 4.3, h: 5.0,
          fontSize: 11, fontFace: this.bodyFont(fonts),
          color: this.hex(palette.text), valign: 'top',
          lineSpacingMultiple: 1.3,
        });
      }
    }
  }

  // ── Chart Slide ──
  // Renders actual PptxGenJS charts from financial data.

  private buildChartSlide(
    slide: any, plan: ContentSlide, palette: ColorPalette, fonts: FontSpec[], contents: SlideContent[],
  ) {
    this.addSlideTitle(slide, plan.title, palette, fonts);
    contents.push({ type: 'text', placeholder: 'title', value: plan.title });

    const chartBlock = (plan.content_blocks || []).find(b => b.type === 'chart');

    if (chartBlock?.content?.data) {
      // Build actual chart from data
      const chartData = chartBlock.content.data;
      const chartType = chartBlock.content.chartType || 'bar';

      try {
        const chartConfig: any = {
          x: 0.5, y: 1.4, w: 9.0, h: 5.0,
          showTitle: false,
          showLegend: true,
          legendPos: 'b',
          legendFontSize: 8,
          catAxisLabelFontSize: 8,
          valAxisLabelFontSize: 8,
          catAxisOrientation: 'minMax',
          valAxisOrientation: 'minMax',
          chartColors: templateAnalysis_colors(palette),
        };

        if (chartType === 'bar' || chartType === 'column') {
          slide.addChart(pptx_chartType('bar'), chartData, chartConfig);
        } else if (chartType === 'line') {
          slide.addChart(pptx_chartType('line'), chartData, chartConfig);
        } else if (chartType === 'pie') {
          slide.addChart(pptx_chartType('pie'), chartData, { ...chartConfig, showPercent: true });
        }

        contents.push({ type: 'chart' as any, placeholder: 'chart', value: chartBlock.content });
      } catch {
        // Fallback to text if chart rendering fails
        slide.addText('Chart: ' + (chartBlock.content.title || plan.title), {
          x: 0.5, y: 1.4, w: 9.0, h: 5.0,
          fontSize: 14, fontFace: this.bodyFont(fonts),
          color: '999999', align: 'center', valign: 'middle',
        });
      }
    } else {
      // No chart data — render content as regular slide
      this.buildContentSlide(slide, plan, palette, fonts, contents);
    }
  }

  // ── Executive Summary ──
  // Left column: key bullets. Right column: highlight box.

  private buildExecutiveSummary(
    slide: any, plan: ContentSlide, palette: ColorPalette, fonts: FontSpec[], contents: SlideContent[],
  ) {
    this.addSlideTitle(slide, plan.title, palette, fonts);
    contents.push({ type: 'text', placeholder: 'title', value: plan.title });

    // Right column highlight box
    slide.addShape('roundRect', {
      x: 6.3, y: 1.3, w: 3.2, h: 5.2,
      fill: { color: 'F0F4F8' }, rectRadius: 0.08,
      line: { color: this.hex(palette.primary), width: 0.5 },
    });

    slide.addText('Key Highlights', {
      x: 6.5, y: 1.5, w: 2.8, h: 0.4,
      fontSize: 12, fontFace: this.titleFont(fonts), bold: true,
      color: this.hex(palette.primary),
    });

    const bulletBlock = (plan.content_blocks || []).find(b => b.type === 'bullet_list');
    if (bulletBlock && Array.isArray(bulletBlock.content)) {
      // First 3 bullets go in the highlight box
      const highlights = bulletBlock.content.slice(0, 3);
      const remaining = bulletBlock.content.slice(3);

      const highlightText = highlights.map((item: string, i: number) => ({
        text: item,
        options: {
          fontSize: 10, fontFace: this.bodyFont(fonts),
          color: this.hex(palette.text),
          bullet: { type: 'number' },
          paraSpaceBefore: 3, paraSpaceAfter: 6,
        },
      }));

      slide.addText(highlightText, { x: 6.5, y: 2.0, w: 2.8, h: 4.0, valign: 'top' });

      // Remaining bullets in left column
      if (remaining.length > 0) {
        const bodyBullets = remaining.map((item: string) => ({
          text: item,
          options: {
            fontSize: 11, fontFace: this.bodyFont(fonts),
            color: this.hex(palette.text),
            bullet: { type: 'bullet', char: '●', indent: 14 },
            paraSpaceBefore: 2, paraSpaceAfter: 6,
          },
        }));
        slide.addText(bodyBullets, { x: 0.5, y: 1.3, w: 5.5, h: 5.2, valign: 'top' });
      }

      contents.push({ type: 'list', placeholder: 'body', value: bulletBlock.content });
    }

    // Paragraph content in left column
    const paraBlock = (plan.content_blocks || []).find(b => b.type === 'paragraph');
    if (paraBlock) {
      slide.addText(String(paraBlock.content), {
        x: 0.5, y: 1.3, w: 5.5, h: 5.2,
        fontSize: 11, fontFace: this.bodyFont(fonts),
        color: this.hex(palette.text),
        valign: 'top', lineSpacingMultiple: 1.4,
      });
    }
  }

  // ── Helpers ──

  /** Add standardised slide title with accent underline */
  private addSlideTitle(slide: any, title: string, palette: ColorPalette, fonts: FontSpec[]) {
    slide.addText(title, {
      x: 0.5, y: 0.2, w: 9.0, h: 0.65,
      fontSize: 20, fontFace: this.titleFont(fonts), bold: true,
      color: this.hex(palette.primary),
      valign: 'bottom',
    });
    // Accent underline
    slide.addShape('line', {
      x: 0.5, y: 0.92, w: 9.0, h: 0,
      line: { color: this.hex(palette.primary), width: 0.8 },
    });
  }

  /** Add slide number in bottom right */
  private addSlideNumber(slide: any, num: number, fonts: FontSpec[]) {
    slide.addText(String(num), {
      x: 9.2, y: 7.05, w: 0.6, h: 0.3,
      fontSize: 7, fontFace: this.bodyFont(fonts),
      color: '999999', align: 'right',
    });
  }

  /** Add speaker notes */
  private addSlideNotes(slide: any, plan: ContentSlide) {
    if (plan.talking_points?.length) {
      slide.addNotes(plan.talking_points.join('\n'));
    }
  }

  /** Strip # prefix from hex colour */
  private hex(color: string): string {
    return (color || '333333').replace('#', '');
  }

  /** Get title font name from extracted fonts */
  private titleFont(fonts: FontSpec[]): string {
    return fonts[0]?.name || 'Calibri';
  }

  /** Get body font name from extracted fonts */
  private bodyFont(fonts: FontSpec[]): string {
    return fonts[2]?.name || fonts[0]?.name || 'Calibri';
  }

  /** Get first content block of a given type */
  private getBlockContent(plan: ContentSlide, type: string): string | null {
    const block = (plan.content_blocks || []).find(b => b.type === type);
    return block ? String(block.content) : null;
  }

  /** Get all content blocks of a given type */
  private getAllBlockContent(plan: ContentSlide, type: string): string[] {
    return (plan.content_blocks || [])
      .filter(b => b.type === type)
      .map(b => String(b.content));
  }
}

// Chart type helper (PptxGenJS uses different type names)
function pptx_chartType(type: string): any {
  const PptxGenJS = require('pptxgenjs');
  const map: Record<string, any> = {
    bar: PptxGenJS.charts?.BAR || 'bar',
    line: PptxGenJS.charts?.LINE || 'line',
    pie: PptxGenJS.charts?.PIE || 'pie',
    area: PptxGenJS.charts?.AREA || 'area',
  };
  return map[type] || map.bar;
}

// Extract chart colours from palette
function templateAnalysis_colors(palette: ColorPalette): string[] {
  return palette.colors.map(c => c.replace('#', ''));
}

export const slideBuilder = new SlideBuilderService();
