import PptxGenJS from 'pptxgenjs';
import type { ContentPlan, TemplateAnalysis, SlideData, SlideContent } from '@pitchdeck/shared-types';

/**
 * Slide Builder Service
 *
 * Assembles PowerPoint slides matching template layouts and
 * populates placeholders with generated content.
 */
export class SlideBuilderService {

  /**
   * Build a complete .pptx file from a content plan and template analysis.
   * Returns the file as a Buffer.
   */
  async buildPresentation(contentPlan: ContentPlan, templateAnalysis: TemplateAnalysis): Promise<{ buffer: Buffer; slidesData: SlideData[] }> {
    const pptx = new PptxGenJS();

    // Apply template styling
    this.applyTemplateStyles(pptx, templateAnalysis);

    const slidesData: SlideData[] = [];

    for (const slidePlan of contentPlan.slides) {
      const slide = pptx.addSlide();
      const layout = templateAnalysis.slide_layouts.find(l => l.name === slidePlan.layout)
        || templateAnalysis.slide_layouts[2]; // Default to Content Slide

      const slideContents: SlideContent[] = [];

      // Apply slide background
      slide.background = { color: templateAnalysis.color_palette.background.replace('#', '') };

      switch (slidePlan.layout) {
        case 'Title Slide':
          this.buildTitleSlide(slide, slidePlan, templateAnalysis, slideContents);
          break;
        case 'Section Header':
          this.buildSectionHeader(slide, slidePlan, templateAnalysis, slideContents);
          break;
        case 'Financial Table':
          this.buildFinancialTable(slide, slidePlan, templateAnalysis, slideContents);
          break;
        case 'Key Metrics':
          this.buildKeyMetrics(slide, slidePlan, templateAnalysis, slideContents);
          break;
        case 'Two Column':
          this.buildTwoColumn(slide, slidePlan, templateAnalysis, slideContents);
          break;
        case 'Chart Slide':
          this.buildChartSlide(slide, slidePlan, templateAnalysis, slideContents);
          break;
        default:
          this.buildContentSlide(slide, slidePlan, templateAnalysis, slideContents);
          break;
      }

      // Add slide number
      slide.addText(String(slidePlan.index + 1), {
        x: 9.0, y: 6.8, w: 0.5, h: 0.3,
        fontSize: 8, color: '999999', align: 'right',
      });

      slidesData.push({
        index: slidePlan.index,
        title: slidePlan.title,
        layout: slidePlan.layout,
        content: slideContents,
        notes: slidePlan.talking_points?.join('\n'),
      });

      // Add speaker notes
      if (slidePlan.talking_points?.length) {
        slide.addNotes(slidePlan.talking_points.join('\n'));
      }
    }

    const output = await pptx.write({ outputType: 'nodebuffer' }) as Buffer;

    return { buffer: output, slidesData };
  }

  private applyTemplateStyles(pptx: PptxGenJS, analysis: TemplateAnalysis) {
    pptx.layout = 'LAYOUT_WIDE'; // 13.33 x 7.5 inches
    pptx.author = 'AI Pitch Deck Builder';
    pptx.company = 'Generated by AI';

    // Set theme colors
    if (analysis.color_palette) {
      // PptxGenJS doesn't support theme colors directly,
      // but we use the palette throughout slide building
    }
  }

  private buildTitleSlide(slide: any, plan: any, analysis: TemplateAnalysis, contents: SlideContent[]) {
    const palette = analysis.color_palette;

    // Background accent bar
    slide.addShape('rect', {
      x: 0, y: 0, w: '100%', h: 0.15,
      fill: { color: palette.primary.replace('#', '') },
    });

    // Title
    const titleBlock = plan.content_blocks?.find((b: any) => b.type === 'heading');
    slide.addText(titleBlock?.content || plan.title, {
      x: 0.8, y: 2.0, w: 8.5, h: 1.5,
      fontSize: 36, fontFace: 'Calibri', bold: true,
      color: palette.primary.replace('#', ''),
      align: 'left',
    });
    contents.push({ type: 'text', placeholder: 'title', value: titleBlock?.content || plan.title });

    // Subtitle
    const subtitleBlock = plan.content_blocks?.find((b: any) => b.type === 'paragraph');
    if (subtitleBlock) {
      slide.addText(subtitleBlock.content, {
        x: 0.8, y: 3.6, w: 8.5, h: 0.8,
        fontSize: 18, fontFace: 'Calibri',
        color: palette.secondary.replace('#', ''),
      });
      contents.push({ type: 'text', placeholder: 'subtitle', value: subtitleBlock.content });
    }

    // Date
    const dateBlock = plan.content_blocks?.find((b: any) => b.type === 'paragraph' && b !== subtitleBlock);
    if (dateBlock) {
      slide.addText(dateBlock.content, {
        x: 0.8, y: 5.5, w: 4.0, h: 0.5,
        fontSize: 12, fontFace: 'Calibri',
        color: '666666',
      });
    }

    // Confidential notice
    slide.addText('CONFIDENTIAL', {
      x: 0.8, y: 6.3, w: 4.0, h: 0.3,
      fontSize: 9, fontFace: 'Calibri',
      color: '999999', italic: true,
    });

    // Bottom accent bar
    slide.addShape('rect', {
      x: 0, y: 7.35, w: '100%', h: 0.15,
      fill: { color: palette.primary.replace('#', '') },
    });
  }

  private buildSectionHeader(slide: any, plan: any, analysis: TemplateAnalysis, contents: SlideContent[]) {
    const palette = analysis.color_palette;

    slide.background = { color: palette.primary.replace('#', '') };
    slide.addText(plan.title, {
      x: 0.8, y: 2.5, w: 8.5, h: 2.0,
      fontSize: 32, fontFace: 'Calibri', bold: true,
      color: 'FFFFFF', align: 'left',
    });
    contents.push({ type: 'text', placeholder: 'title', value: plan.title });
  }

  private buildContentSlide(slide: any, plan: any, analysis: TemplateAnalysis, contents: SlideContent[]) {
    const palette = analysis.color_palette;

    // Top accent line
    slide.addShape('rect', {
      x: 0, y: 0, w: '100%', h: 0.05,
      fill: { color: palette.primary.replace('#', '') },
    });

    // Title
    slide.addText(plan.title, {
      x: 0.5, y: 0.3, w: 9.0, h: 0.7,
      fontSize: 22, fontFace: 'Calibri', bold: true,
      color: palette.primary.replace('#', ''),
    });
    contents.push({ type: 'text', placeholder: 'title', value: plan.title });

    // Content blocks
    let yPos = 1.2;
    for (const block of (plan.content_blocks || [])) {
      if (block.type === 'heading') continue; // Already used as title

      if (block.type === 'bullet_list' && Array.isArray(block.content)) {
        const bulletText = block.content.map((item: string) => ({
          text: item,
          options: { fontSize: 13, fontFace: 'Calibri', color: palette.text.replace('#', ''), bullet: { type: 'bullet' }, paraSpaceAfter: 6 },
        }));

        slide.addText(bulletText, {
          x: 0.5, y: yPos, w: 9.0, h: Math.min(block.content.length * 0.45, 5.0),
          valign: 'top',
        });
        contents.push({ type: 'list', placeholder: 'body', value: block.content });
        yPos += block.content.length * 0.4;
      } else if (block.type === 'paragraph') {
        slide.addText(String(block.content), {
          x: 0.5, y: yPos, w: 9.0, h: 1.0,
          fontSize: 13, fontFace: 'Calibri',
          color: palette.text.replace('#', ''),
          valign: 'top',
        });
        contents.push({ type: 'text', placeholder: 'body', value: block.content });
        yPos += 1.0;
      }
    }
  }

  private buildFinancialTable(slide: any, plan: any, analysis: TemplateAnalysis, contents: SlideContent[]) {
    const palette = analysis.color_palette;

    // Top accent line
    slide.addShape('rect', {
      x: 0, y: 0, w: '100%', h: 0.05,
      fill: { color: palette.primary.replace('#', '') },
    });

    // Title
    slide.addText(plan.title, {
      x: 0.5, y: 0.3, w: 9.0, h: 0.7,
      fontSize: 22, fontFace: 'Calibri', bold: true,
      color: palette.primary.replace('#', ''),
    });

    const tableBlock = plan.content_blocks?.find((b: any) => b.type === 'table');
    if (tableBlock?.content) {
      const { headers, rows } = tableBlock.content;
      const tableData: any[][] = [];

      // Header row
      if (headers) {
        tableData.push(headers.map((h: string) => ({
          text: h,
          options: {
            bold: true, fontSize: 11, fontFace: 'Calibri',
            color: 'FFFFFF',
            fill: { color: palette.primary.replace('#', '') },
            align: 'center', valign: 'middle',
          },
        })));
      }

      // Data rows
      for (let i = 0; i < (rows || []).length; i++) {
        const row = rows[i];
        const isEven = i % 2 === 0;
        tableData.push(row.map((cell: string, j: number) => ({
          text: String(cell),
          options: {
            fontSize: 10, fontFace: 'Calibri',
            color: palette.text.replace('#', ''),
            fill: { color: isEven ? 'F5F5F5' : 'FFFFFF' },
            align: j === 0 ? 'left' : 'right',
            valign: 'middle',
          },
        })));
      }

      if (tableData.length > 0) {
        slide.addTable(tableData, {
          x: 0.5, y: 1.3, w: 9.0,
          border: { type: 'solid', pt: 0.5, color: 'CCCCCC' },
          rowH: 0.4,
          colW: headers ? Array(headers.length).fill(9.0 / headers.length) : [4.5, 4.5],
        });
        contents.push({ type: 'table', placeholder: 'table', value: tableBlock.content });
      }
    }
  }

  private buildKeyMetrics(slide: any, plan: any, analysis: TemplateAnalysis, contents: SlideContent[]) {
    const palette = analysis.color_palette;

    // Top accent line
    slide.addShape('rect', {
      x: 0, y: 0, w: '100%', h: 0.05,
      fill: { color: palette.primary.replace('#', '') },
    });

    // Title
    slide.addText(plan.title, {
      x: 0.5, y: 0.3, w: 9.0, h: 0.7,
      fontSize: 22, fontFace: 'Calibri', bold: true,
      color: palette.primary.replace('#', ''),
    });

    const metricBlocks = (plan.content_blocks || []).filter((b: any) => b.type === 'metric');
    const count = metricBlocks.length || 3;
    const cardWidth = (9.0 - (count - 1) * 0.3) / count;

    metricBlocks.forEach((block: any, i: number) => {
      const x = 0.5 + i * (cardWidth + 0.3);
      const y = 1.5;

      // Card background
      slide.addShape('roundRect', {
        x, y, w: cardWidth, h: 2.5,
        fill: { color: 'F8F9FA' },
        rectRadius: 0.1,
        shadow: { type: 'outer', blur: 3, offset: 2, color: '000000', opacity: 0.1 },
      });

      // Metric value
      slide.addText(block.content?.value || 'N/A', {
        x, y: y + 0.4, w: cardWidth, h: 1.0,
        fontSize: 28, fontFace: 'Calibri', bold: true,
        color: palette.primary.replace('#', ''),
        align: 'center',
      });

      // Metric label
      slide.addText(block.content?.label || '', {
        x, y: y + 1.4, w: cardWidth, h: 0.6,
        fontSize: 12, fontFace: 'Calibri',
        color: '666666',
        align: 'center',
      });

      contents.push({ type: 'text', placeholder: `metric_${i}`, value: block.content });
    });
  }

  private buildTwoColumn(slide: any, plan: any, analysis: TemplateAnalysis, contents: SlideContent[]) {
    const palette = analysis.color_palette;

    slide.addShape('rect', {
      x: 0, y: 0, w: '100%', h: 0.05,
      fill: { color: palette.primary.replace('#', '') },
    });

    slide.addText(plan.title, {
      x: 0.5, y: 0.3, w: 9.0, h: 0.7,
      fontSize: 22, fontFace: 'Calibri', bold: true,
      color: palette.primary.replace('#', ''),
    });

    const nonHeadingBlocks = (plan.content_blocks || []).filter((b: any) => b.type !== 'heading');

    // Left column
    const leftContent = nonHeadingBlocks[0];
    if (leftContent) {
      if (leftContent.type === 'bullet_list' && Array.isArray(leftContent.content)) {
        const half = Math.ceil(leftContent.content.length / 2);
        const leftItems = leftContent.content.slice(0, half);
        const rightItems = leftContent.content.slice(half);

        const formatBullets = (items: string[]) => items.map((item: string) => ({
          text: item,
          options: { fontSize: 12, fontFace: 'Calibri', color: palette.text.replace('#', ''), bullet: { type: 'bullet' }, paraSpaceAfter: 4 },
        }));

        slide.addText(formatBullets(leftItems), { x: 0.5, y: 1.3, w: 4.2, h: 5.0, valign: 'top' });
        slide.addText(formatBullets(rightItems), { x: 5.3, y: 1.3, w: 4.2, h: 5.0, valign: 'top' });
      } else {
        slide.addText(String(leftContent.content), {
          x: 0.5, y: 1.3, w: 4.2, h: 5.0,
          fontSize: 12, fontFace: 'Calibri',
          color: palette.text.replace('#', ''),
          valign: 'top',
        });
      }
    }

    contents.push({ type: 'text', placeholder: 'body', value: nonHeadingBlocks.map((b: any) => b.content) });
  }

  private buildChartSlide(slide: any, plan: any, analysis: TemplateAnalysis, contents: SlideContent[]) {
    // Charts require actual data; for now render as content slide with chart placeholder
    this.buildContentSlide(slide, plan, analysis, contents);
  }
}

export const slideBuilder = new SlideBuilderService();
