import PptxGenJS from 'pptxgenjs';
import type {
  ContentPlan, ContentSlide, TemplateAnalysis, SlideData, SlideContent,
  ColorPalette, FontSpec, SlideLayout, Placeholder,
} from '@pitchdeck/shared-types';
import { getDefaultTheme, type DefaultTheme } from './default-themes';
import { imageSource } from './image-source.service';

// Slide dimensions for LAYOUT_WIDE
const SW = 13.33; // slide width
const SH = 7.5;   // slide height

// Safe content margins
const MARGIN = 0.6;
const CONTENT_W = SW - MARGIN * 2; // ~12.13

/**
 * Slide Builder Service
 *
 * Two modes:
 *
 * 1. Default mode (no template) — modern, varied layouts inspired by
 *    Gamma-style presentations. Each slide type gets a unique visual
 *    treatment. No repetitive sidebar pattern.
 *
 * 2. Template mode — places content at the exact placeholder positions
 *    extracted from the uploaded .pptx template.
 */
export class SlideBuilderService {

  async buildPresentation(
    contentPlan: ContentPlan,
    templateAnalysis: TemplateAnalysis,
    options?: { pbType?: string; company?: string; ticker?: string; colorTheme?: string; designStyle?: string },
  ): Promise<{ buffer: Buffer; slidesData: SlideData[] }> {
    const pptx = new PptxGenJS();
    const isDefault = templateAnalysis.master_slides.length === 0;
    const theme = isDefault ? getDefaultTheme(options?.pbType, options?.colorTheme) : null;
    const palette = theme ? theme.palette : templateAnalysis.color_palette;
    const fonts = templateAnalysis.fonts;

    pptx.layout = 'LAYOUT_WIDE';
    pptx.author = 'AI Pitch Deck Builder';
    pptx.company = options?.company || 'Generated by AI';
    pptx.subject = contentPlan.title;

    // Pre-fetch images and company logo in parallel
    const [images, companyLogo] = await Promise.all([
      this.prefetchImages(isDefault, contentPlan, options?.company),
      this.fetchCompanyLogo(options?.company, options?.ticker),
    ]);

    const slidesData: SlideData[] = [];

    for (const slidePlan of contentPlan.slides) {
      const slideContents: SlideContent[] = [];
      const layout = this.findLayout(slidePlan.layout, templateAnalysis);
      const img = images.get(`slide_${slidePlan.index}`) || null;
      let slide: any;

      if (!isDefault) {
        // ── TEMPLATE MODE ──
        const masterName = this.masterName(slidePlan.layout);
        slide = pptx.addSlide({ masterName: masterName });
        this.buildTemplateSlide(slide, slidePlan, palette, fonts, slideContents, layout, companyLogo);
      } else if (theme) {
        // ── DEFAULT MODE — varied visual layouts ──
        slide = pptx.addSlide();

        switch (slidePlan.layout) {
          case 'Title Slide':
            this.buildTitle(slide, slidePlan, palette, fonts, slideContents, theme, img, companyLogo);
            break;
          case 'Section Header':
            this.buildSection(slide, slidePlan, palette, fonts, slideContents, theme, img);
            break;
          case 'Executive Summary':
            this.buildExecSummary(slide, slidePlan, palette, fonts, slideContents, theme);
            break;
          case 'Key Metrics':
            this.buildMetrics(slide, slidePlan, palette, fonts, slideContents, theme);
            break;
          case 'Financial Table':
          case 'Comparison Table':
            this.buildTable(slide, slidePlan, palette, fonts, slideContents, theme);
            break;
          case 'Two Column':
            this.buildTwoColumn(slide, slidePlan, palette, fonts, slideContents, theme, img);
            break;
          case 'Chart Slide':
            this.buildChart(slide, pptx, slidePlan, palette, fonts, slideContents, theme);
            break;
          default:
            this.buildContent(slide, slidePlan, palette, fonts, slideContents, theme);
            break;
        }
      }

      if (slide) {
        this.addNotes(slide, slidePlan);
        slidesData.push({
          index: slidePlan.index,
          title: slidePlan.title,
          layout: slidePlan.layout,
          content: slideContents,
          notes: slidePlan.talking_points?.join('\n'),
        });
      }
    }

    const output = await pptx.write({ outputType: 'nodebuffer' }) as Buffer;
    return { buffer: output, slidesData };
  }

  // ──────────────────────────────────────────────
  //  IMAGE PRE-FETCH
  // ──────────────────────────────────────────────

  private async prefetchImages(
    isDefault: boolean, plan: ContentPlan, company?: string,
  ): Promise<Map<string, string>> {
    if (!isDefault) return new Map();

    const queries: { key: string; query: string; orientation?: 'landscape' | 'portrait' }[] = [];

    for (const slide of plan.slides) {
      if (['Title Slide', 'Section Header', 'Two Column'].includes(slide.layout)) {
        queries.push({
          key: `slide_${slide.index}`,
          query: imageSource.queryForSlide(slide.title, company),
          orientation: slide.layout === 'Title Slide' ? 'landscape' : 'landscape',
        });
      }
      if (queries.length >= 4) break;
    }

    if (queries.length === 0) return new Map();
    return imageSource.fetchMultiple(queries);
  }

  // ══════════════════════════════════════════════
  //  DEFAULT MODE — MODERN VARIED LAYOUTS
  // ══════════════════════════════════════════════

  // ──────────────────────────────────────────────
  //  TITLE SLIDE — full-bleed hero
  // ──────────────────────────────────────────────

  private buildTitle(
    slide: any, plan: ContentSlide, palette: ColorPalette, fonts: FontSpec[],
    contents: SlideContent[], theme: DefaultTheme, image: string | null,
    logo: string | null = null,
  ) {
    // Full dark background
    slide.background = { color: this.hex(palette.primary) };

    // Gradient overlay layer
    slide.addShape('rect', {
      x: 0, y: 0, w: SW, h: SH,
      fill: { color: this.hex(theme.sectionBgLayers[1] || palette.secondary) },
      transparency: 60,
    });

    // Background image (right half, with overlay)
    if (image) {
      slide.addImage({
        data: image, x: SW * 0.4, y: 0, w: SW * 0.6, h: SH,
        sizing: { type: 'cover', w: SW * 0.6, h: SH },
      });
      slide.addShape('rect', {
        x: SW * 0.4, y: 0, w: SW * 0.6, h: SH,
        fill: { color: this.hex(palette.primary) }, transparency: 50,
      });
      // Soft gradient from left
      slide.addShape('rect', {
        x: 0, y: 0, w: SW * 0.55, h: SH,
        fill: { color: this.hex(palette.primary) },
      });
    }

    // Large decorative circle (top-right, subtle)
    slide.addShape('ellipse', {
      x: SW * 0.65, y: -1.5, w: 5, h: 5,
      fill: { color: this.hex(theme.decorSecondary) }, transparency: 85,
    });
    // Small accent circle
    slide.addShape('ellipse', {
      x: SW * 0.75, y: SH - 3, w: 3, h: 3,
      fill: { color: 'FFFFFF' }, transparency: 92,
    });

    // Company logo (top-left)
    if (logo) {
      try {
        slide.addImage({
          data: logo, x: MARGIN, y: 0.5, w: 1.1, h: 1.1,
          sizing: { type: 'contain', w: 1.1, h: 1.1 },
        });
      } catch { /* skip */ }
    }

    // Accent line
    const titleY = logo ? 2.2 : 1.8;
    slide.addShape('rect', {
      x: MARGIN, y: titleY, w: 2.5, h: 0.06,
      fill: { color: this.hex(theme.decorSecondary) },
    });

    // Main title
    const titleText = this.getBlockContent(plan, 'heading') || plan.title;
    slide.addText(titleText, {
      x: MARGIN, y: titleY + 0.25, w: SW * 0.5, h: 2.0,
      fontSize: 38, fontFace: this.titleFont(fonts), bold: true,
      color: 'FFFFFF', align: 'left', valign: 'top',
      lineSpacingMultiple: 1.05,
    });
    contents.push({ type: 'text', placeholder: 'title', value: titleText });

    // Subtitle
    const paragraphs = this.getAllBlockContent(plan, 'paragraph');
    if (paragraphs.length > 0) {
      slide.addText(paragraphs[0], {
        x: MARGIN, y: titleY + 2.4, w: SW * 0.45, h: 0.8,
        fontSize: 16, fontFace: this.bodyFont(fonts),
        color: this.hex(theme.decorSecondary), align: 'left',
      });
      contents.push({ type: 'text', placeholder: 'subtitle', value: paragraphs[0] });
    }

    // Date
    const dateText = paragraphs.length > 1
      ? paragraphs[1]
      : new Date().toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
    slide.addText(dateText, {
      x: MARGIN, y: SH - 1.3, w: 4.0, h: 0.4,
      fontSize: 12, fontFace: this.bodyFont(fonts), color: 'BBBBBB',
    });

    // Confidential footer
    slide.addText('CONFIDENTIAL', {
      x: MARGIN, y: SH - 0.6, w: 4, h: 0.3,
      fontSize: 8, fontFace: this.bodyFont(fonts), color: '888888', italic: true,
    });

    // Bottom accent bar
    slide.addShape('rect', {
      x: 0, y: SH - 0.08, w: SW, h: 0.08,
      fill: { color: this.hex(theme.decorSecondary) },
    });
  }

  // ──────────────────────────────────────────────
  //  SECTION HEADER — bold, centered
  // ──────────────────────────────────────────────

  private buildSection(
    slide: any, plan: ContentSlide, palette: ColorPalette, fonts: FontSpec[],
    contents: SlideContent[], theme: DefaultTheme, image: string | null,
  ) {
    slide.background = { color: this.hex(palette.primary) };

    if (image) {
      slide.addImage({ data: image, x: 0, y: 0, w: SW, h: SH, sizing: { type: 'cover', w: SW, h: SH } });
      slide.addShape('rect', { x: 0, y: 0, w: SW, h: SH, fill: { color: this.hex(palette.primary) }, transparency: 35 });
    }

    // Gradient layer
    slide.addShape('rect', {
      x: SW * 0.4, y: 0, w: SW * 0.6, h: SH,
      fill: { color: this.hex(theme.sectionBgLayers[2] || palette.secondary) }, transparency: 55,
    });

    // Decorative shapes
    slide.addShape('ellipse', {
      x: SW - 4, y: -2, w: 6, h: 6,
      fill: { color: this.hex(theme.decorSecondary) }, transparency: 88,
    });

    // Large section number (left)
    slide.addText(String(plan.index + 1).padStart(2, '0'), {
      x: MARGIN, y: 1.0, w: 4, h: 2.5,
      fontSize: 96, fontFace: this.titleFont(fonts), bold: true,
      color: 'FFFFFF', transparency: 75,
    });

    // Accent line
    slide.addShape('rect', {
      x: MARGIN, y: 3.6, w: 3, h: 0.06,
      fill: { color: this.hex(theme.decorSecondary) },
    });

    // Section title
    slide.addText(plan.title, {
      x: MARGIN, y: 3.9, w: SW * 0.7, h: 2.0,
      fontSize: 36, fontFace: this.titleFont(fonts), bold: true,
      color: 'FFFFFF', align: 'left', valign: 'top',
    });
    contents.push({ type: 'text', placeholder: 'title', value: plan.title });

    // Bottom bar
    slide.addShape('rect', {
      x: 0, y: SH - 0.08, w: SW, h: 0.08,
      fill: { color: this.hex(theme.decorSecondary) },
    });
  }

  // ──────────────────────────────────────────────
  //  CONTENT SLIDE — clean full-width layout
  // ──────────────────────────────────────────────

  private buildContent(
    slide: any, plan: ContentSlide, palette: ColorPalette, fonts: FontSpec[],
    contents: SlideContent[], theme: DefaultTheme,
  ) {
    slide.background = { color: this.hex(palette.background) };

    // Top accent bar
    slide.addShape('rect', { x: 0, y: 0, w: SW, h: 0.06, fill: { color: this.hex(palette.primary) } });

    // Title with colored left accent
    slide.addShape('rect', {
      x: MARGIN - 0.15, y: 0.5, w: 0.06, h: 0.6,
      fill: { color: this.hex(theme.decorSecondary) },
    });
    slide.addText(plan.title, {
      x: MARGIN + 0.1, y: 0.4, w: CONTENT_W - 0.1, h: 0.8,
      fontSize: 24, fontFace: this.titleFont(fonts), bold: true,
      color: this.hex(palette.primary), valign: 'middle',
    });
    contents.push({ type: 'text', placeholder: 'title', value: plan.title });

    // Content area
    let yPos = 1.5;
    const maxY = SH - 0.8;
    const cx = MARGIN;
    const cw = CONTENT_W;

    for (const block of (plan.content_blocks || [])) {
      if (block.type === 'heading') continue;
      if (yPos > maxY - 0.5) break;

      if (block.type === 'bullet_list' && Array.isArray(block.content)) {
        const bulletRows = block.content.map((item: string) => ({
          text: item,
          options: {
            fontSize: 13, fontFace: this.bodyFont(fonts),
            color: this.hex(palette.text),
            bullet: { type: 'bullet' as const, char: '\u25B8', indent: 20 },
            paraSpaceBefore: 4, paraSpaceAfter: 10,
          },
        }));

        const height = Math.min(block.content.length * 0.5 + 0.2, maxY - yPos);
        slide.addText(bulletRows, { x: cx + 0.2, y: yPos, w: cw - 0.4, h: height, valign: 'top' });
        contents.push({ type: 'list', placeholder: 'body', value: block.content });
        yPos += height + 0.15;
      } else if (block.type === 'paragraph') {
        const text = String(block.content);
        const height = Math.max(Math.ceil(text.length / 120) * 0.4, 0.5);
        slide.addText(text, {
          x: cx, y: yPos, w: cw, h: Math.min(height, maxY - yPos),
          fontSize: 13, fontFace: this.bodyFont(fonts),
          color: this.hex(palette.text), valign: 'top', lineSpacingMultiple: 1.5,
        });
        contents.push({ type: 'text', placeholder: 'body', value: text });
        yPos += height + 0.2;
      }
    }

    this.addFooter(slide, plan.index + 1, fonts, palette, theme);
  }

  // ──────────────────────────────────────────────
  //  EXECUTIVE SUMMARY — hero card layout
  // ──────────────────────────────────────────────

  private buildExecSummary(
    slide: any, plan: ContentSlide, palette: ColorPalette, fonts: FontSpec[],
    contents: SlideContent[], theme: DefaultTheme,
  ) {
    slide.background = { color: this.hex(palette.background) };

    // Top accent bar
    slide.addShape('rect', { x: 0, y: 0, w: SW, h: 0.06, fill: { color: this.hex(palette.primary) } });

    // Title
    slide.addShape('rect', {
      x: MARGIN - 0.15, y: 0.5, w: 0.06, h: 0.6,
      fill: { color: this.hex(theme.decorSecondary) },
    });
    slide.addText(plan.title, {
      x: MARGIN + 0.1, y: 0.4, w: CONTENT_W * 0.6, h: 0.8,
      fontSize: 24, fontFace: this.titleFont(fonts), bold: true,
      color: this.hex(palette.primary), valign: 'middle',
    });
    contents.push({ type: 'text', placeholder: 'title', value: plan.title });

    // Split: left body (60%) + right highlight card (35%)
    const leftW = CONTENT_W * 0.58;
    const rightW = CONTENT_W * 0.37;
    const rightX = MARGIN + CONTENT_W - rightW;
    const cardY = 1.5;
    const cardH = SH - cardY - 0.8;

    // Left: body content
    const bulletBlock = (plan.content_blocks || []).find(b => b.type === 'bullet_list');
    const paraBlock = (plan.content_blocks || []).find(b => b.type === 'paragraph');

    if (paraBlock) {
      slide.addText(String(paraBlock.content), {
        x: MARGIN, y: cardY, w: leftW, h: Math.min(2.0, cardH),
        fontSize: 13, fontFace: this.bodyFont(fonts),
        color: this.hex(palette.text), valign: 'top', lineSpacingMultiple: 1.5,
      });
    }

    if (bulletBlock && Array.isArray(bulletBlock.content)) {
      const startY = paraBlock ? cardY + 2.2 : cardY;
      const remaining = bulletBlock.content.slice(3); // Non-highlight bullets
      if (remaining.length > 0) {
        const bullets = remaining.map((item: string) => ({
          text: item,
          options: {
            fontSize: 12, fontFace: this.bodyFont(fonts), color: this.hex(palette.text),
            bullet: { type: 'bullet' as const, char: '\u25B8', indent: 16 },
            paraSpaceBefore: 3, paraSpaceAfter: 8,
          },
        }));
        slide.addText(bullets, {
          x: MARGIN, y: startY, w: leftW, h: Math.max(cardH - (startY - cardY), 1), valign: 'top',
        });
      }
      contents.push({ type: 'list', placeholder: 'body', value: bulletBlock.content });
    }

    // Right: highlight card
    slide.addShape('roundRect', {
      x: rightX, y: cardY, w: rightW, h: cardH,
      fill: { color: this.hex(theme.panelTint) }, rectRadius: 0.12,
    });
    // Card left accent
    slide.addShape('rect', {
      x: rightX, y: cardY + 0.15, w: 0.06, h: cardH - 0.3,
      fill: { color: this.hex(theme.decorSecondary) },
    });

    slide.addText('KEY HIGHLIGHTS', {
      x: rightX + 0.3, y: cardY + 0.2, w: rightW - 0.5, h: 0.4,
      fontSize: 11, fontFace: this.titleFont(fonts), bold: true,
      color: this.hex(palette.primary),
    });

    if (bulletBlock && Array.isArray(bulletBlock.content)) {
      const highlights = bulletBlock.content.slice(0, 3);
      const hText = highlights.map((item: string, i: number) => ({
        text: `${i + 1}. ${item}`,
        options: {
          fontSize: 11, fontFace: this.bodyFont(fonts), color: this.hex(palette.text),
          paraSpaceBefore: 6, paraSpaceAfter: 10, lineSpacingMultiple: 1.4,
        },
      }));
      slide.addText(hText, {
        x: rightX + 0.3, y: cardY + 0.7, w: rightW - 0.6, h: cardH - 1.0, valign: 'top',
      });
    }

    this.addFooter(slide, plan.index + 1, fonts, palette, theme);
  }

  // ──────────────────────────────────────────────
  //  KEY METRICS — card grid
  // ──────────────────────────────────────────────

  private buildMetrics(
    slide: any, plan: ContentSlide, palette: ColorPalette, fonts: FontSpec[],
    contents: SlideContent[], theme: DefaultTheme,
  ) {
    slide.background = { color: this.hex(palette.background) };

    // Top accent bar
    slide.addShape('rect', { x: 0, y: 0, w: SW, h: 0.06, fill: { color: this.hex(palette.primary) } });

    // Title
    slide.addShape('rect', {
      x: MARGIN - 0.15, y: 0.5, w: 0.06, h: 0.6,
      fill: { color: this.hex(theme.decorSecondary) },
    });
    slide.addText(plan.title, {
      x: MARGIN + 0.1, y: 0.4, w: CONTENT_W - 0.1, h: 0.8,
      fontSize: 24, fontFace: this.titleFont(fonts), bold: true,
      color: this.hex(palette.primary), valign: 'middle',
    });
    contents.push({ type: 'text', placeholder: 'title', value: plan.title });

    const metricBlocks = (plan.content_blocks || []).filter(b => b.type === 'metric');
    const count = metricBlocks.length || 1;
    const maxCols = Math.min(count, 4);
    const gap = 0.3;
    const cardW = (CONTENT_W - (maxCols - 1) * gap) / maxCols;
    const accentColors = [
      palette.primary, theme.decorSecondary, palette.secondary,
      theme.cardAccent, palette.primary,
    ];

    for (let i = 0; i < metricBlocks.length; i++) {
      const col = i % maxCols;
      const row = Math.floor(i / maxCols);
      const x = MARGIN + col * (cardW + gap);
      const y = 1.6 + row * 3.2;
      const block = metricBlocks[i];
      const label = block.content?.label || '';
      const value = block.content?.value || 'N/A';
      const accent = accentColors[i % accentColors.length];

      // Card background
      slide.addShape('roundRect', {
        x, y, w: cardW, h: 2.8,
        fill: { color: 'FFFFFF' }, rectRadius: 0.12,
        shadow: { type: 'outer', blur: 6, offset: 2, color: '000000', opacity: 0.08 },
      });

      // Top accent bar on card
      slide.addShape('rect', {
        x: x + 0.2, y, w: cardW - 0.4, h: 0.06,
        fill: { color: this.hex(accent) },
      });

      // Value
      slide.addText(value, {
        x, y: y + 0.3, w: cardW, h: 1.4,
        fontSize: 32, fontFace: this.titleFont(fonts), bold: true,
        color: this.hex(palette.primary), align: 'center', valign: 'middle',
      });

      // Label
      slide.addText(label, {
        x: x + 0.15, y: y + 1.8, w: cardW - 0.3, h: 0.8,
        fontSize: 11, fontFace: this.bodyFont(fonts),
        color: '666666', align: 'center', valign: 'top',
        lineSpacingMultiple: 1.3,
      });

      contents.push({ type: 'text', placeholder: `metric_${i}`, value: block.content });
    }

    this.addFooter(slide, plan.index + 1, fonts, palette, theme);
  }

  // ──────────────────────────────────────────────
  //  TABLE SLIDE — clean, no sidebar
  // ──────────────────────────────────────────────

  private buildTable(
    slide: any, plan: ContentSlide, palette: ColorPalette, fonts: FontSpec[],
    contents: SlideContent[], theme: DefaultTheme,
  ) {
    slide.background = { color: this.hex(palette.background) };

    // Top accent bar
    slide.addShape('rect', { x: 0, y: 0, w: SW, h: 0.06, fill: { color: this.hex(palette.primary) } });

    // Title
    slide.addShape('rect', {
      x: MARGIN - 0.15, y: 0.5, w: 0.06, h: 0.6,
      fill: { color: this.hex(theme.decorSecondary) },
    });
    slide.addText(plan.title, {
      x: MARGIN + 0.1, y: 0.4, w: CONTENT_W - 0.1, h: 0.8,
      fontSize: 24, fontFace: this.titleFont(fonts), bold: true,
      color: this.hex(palette.primary), valign: 'middle',
    });
    contents.push({ type: 'text', placeholder: 'title', value: plan.title });

    const tableBlock = (plan.content_blocks || []).find(b => b.type === 'table');
    if (!tableBlock?.content) {
      slide.addText('[Financial data table]', {
        x: MARGIN, y: 2.0, w: CONTENT_W, h: 4.0,
        fontSize: 14, fontFace: this.bodyFont(fonts), color: '999999',
        align: 'center', valign: 'middle',
      });
      this.addFooter(slide, plan.index + 1, fonts, palette, theme);
      return;
    }

    const { headers, rows } = tableBlock.content;
    const tableData: any[][] = [];
    const numCols = headers?.length || 2;

    if (headers) {
      tableData.push(headers.map((h: string) => ({
        text: String(h),
        options: {
          bold: true, fontSize: 10, fontFace: this.bodyFont(fonts), color: 'FFFFFF',
          fill: { color: this.hex(palette.primary) },
          align: 'center' as const, valign: 'middle' as const,
          border: [
            { type: 'solid', pt: 0.5, color: this.hex(palette.primary) },
            { type: 'solid', pt: 0.5, color: this.hex(palette.primary) },
            { type: 'solid', pt: 1.5, color: this.hex(theme.decorSecondary) },
            { type: 'solid', pt: 0.5, color: this.hex(palette.primary) },
          ],
          margin: [4, 6, 4, 6],
        },
      })));
    }

    for (let i = 0; i < (rows || []).length; i++) {
      const row = rows[i];
      const bgColor = i % 2 === 0 ? this.hex(theme.panelTint) : 'FFFFFF';

      tableData.push(row.map((cell: string, j: number) => {
        const isNum = j > 0 && /^[\$\u00A3\u20AC\-\d,.\s%xX]+$/.test(String(cell).trim());
        return {
          text: String(cell),
          options: {
            fontSize: 9, fontFace: this.bodyFont(fonts), color: this.hex(palette.text),
            fill: { color: bgColor },
            align: j === 0 ? 'left' as const : (isNum ? 'right' as const : 'center' as const),
            valign: 'middle' as const,
            border: [
              { type: 'solid', pt: 0.3, color: 'E0E0E0' },
              { type: 'solid', pt: 0.3, color: 'E0E0E0' },
              { type: 'solid', pt: 0.3, color: 'E0E0E0' },
              { type: 'solid', pt: 0.3, color: 'E0E0E0' },
            ],
            margin: [3, 6, 3, 6],
          },
        };
      }));
    }

    if (tableData.length > 0) {
      const colWidths = Array(numCols).fill(CONTENT_W / numCols);
      if (numCols > 2) {
        colWidths[0] = Math.min(3.0, CONTENT_W * 0.28);
        const rem = (CONTENT_W - colWidths[0]) / (numCols - 1);
        for (let i = 1; i < numCols; i++) colWidths[i] = rem;
      }

      slide.addTable(tableData, {
        x: MARGIN, y: 1.5, w: CONTENT_W, rowH: 0.38, colW: colWidths,
        border: { type: 'solid', pt: 0, color: 'FFFFFF' },
      });
      contents.push({ type: 'table', placeholder: 'table', value: tableBlock.content });
    }

    // Source
    slide.addText('Source: Yahoo Finance, SEC EDGAR, Company Reports', {
      x: MARGIN, y: SH - 0.7, w: CONTENT_W, h: 0.3,
      fontSize: 7, fontFace: this.bodyFont(fonts), color: '999999', italic: true,
    });

    this.addFooter(slide, plan.index + 1, fonts, palette, theme);
  }

  // ──────────────────────────────────────────────
  //  TWO COLUMN — text + image or split content
  // ──────────────────────────────────────────────

  private buildTwoColumn(
    slide: any, plan: ContentSlide, palette: ColorPalette, fonts: FontSpec[],
    contents: SlideContent[], theme: DefaultTheme, image: string | null,
  ) {
    slide.background = { color: this.hex(palette.background) };

    // Top accent
    slide.addShape('rect', { x: 0, y: 0, w: SW, h: 0.06, fill: { color: this.hex(palette.primary) } });

    // Title
    slide.addShape('rect', {
      x: MARGIN - 0.15, y: 0.5, w: 0.06, h: 0.6,
      fill: { color: this.hex(theme.decorSecondary) },
    });
    slide.addText(plan.title, {
      x: MARGIN + 0.1, y: 0.4, w: CONTENT_W - 0.1, h: 0.8,
      fontSize: 24, fontFace: this.titleFont(fonts), bold: true,
      color: this.hex(palette.primary), valign: 'middle',
    });
    contents.push({ type: 'text', placeholder: 'title', value: plan.title });

    const colY = 1.5;
    const colH = SH - colY - 0.8;
    const gap = 0.4;
    const leftW = (CONTENT_W - gap) * 0.55;
    const rightW = (CONTENT_W - gap) * 0.45;
    const rightX = MARGIN + leftW + gap;

    // Right column: image or second content
    if (image) {
      slide.addShape('roundRect', {
        x: rightX, y: colY, w: rightW, h: colH,
        fill: { color: this.hex(theme.panelTint) }, rectRadius: 0.12,
      });
      slide.addImage({
        data: image, x: rightX + 0.15, y: colY + 0.15,
        w: rightW - 0.3, h: colH - 0.3,
        sizing: { type: 'contain', w: rightW - 0.3, h: colH - 0.3 },
      });
    }

    // Left column: text/bullets
    const nonHeading = (plan.content_blocks || []).filter(b => b.type !== 'heading');

    if (nonHeading.length > 0 && nonHeading[0].type === 'bullet_list' && Array.isArray(nonHeading[0].content)) {
      const items = nonHeading[0].content;

      if (image) {
        // All bullets in left column
        const bullets = items.map((item: string) => ({
          text: item,
          options: {
            fontSize: 12, fontFace: this.bodyFont(fonts), color: this.hex(palette.text),
            bullet: { type: 'bullet' as const, char: '\u25B8', indent: 16 },
            paraSpaceBefore: 4, paraSpaceAfter: 10,
          },
        }));
        slide.addText(bullets, { x: MARGIN, y: colY, w: leftW, h: colH, valign: 'top' });
      } else {
        // No image — split bullets between columns with a divider
        const half = Math.ceil(items.length / 2);
        const fmt = (list: string[]) => list.map((item: string) => ({
          text: item,
          options: {
            fontSize: 12, fontFace: this.bodyFont(fonts), color: this.hex(palette.text),
            bullet: { type: 'bullet' as const, char: '\u25B8', indent: 16 },
            paraSpaceBefore: 3, paraSpaceAfter: 8,
          },
        }));
        slide.addText(fmt(items.slice(0, half)), { x: MARGIN, y: colY, w: leftW, h: colH, valign: 'top' });
        slide.addText(fmt(items.slice(half)), { x: rightX, y: colY, w: rightW, h: colH, valign: 'top' });

        // Subtle divider
        const divX = MARGIN + leftW + gap / 2;
        slide.addShape('line', {
          x: divX, y: colY + 0.2, w: 0, h: colH - 0.4,
          line: { color: 'D0D0D0', width: 0.5 },
        });
      }
      contents.push({ type: 'list', placeholder: 'body', value: items });
    } else {
      // Paragraphs in left, second block in right
      for (let i = 0; i < Math.min(nonHeading.length, 2); i++) {
        const block = nonHeading[i];
        const x = i === 0 ? MARGIN : rightX;
        const w = i === 0 ? leftW : rightW;
        const text = typeof block.content === 'string' ? block.content : JSON.stringify(block.content);
        slide.addText(text, {
          x, y: colY, w, h: colH,
          fontSize: 12, fontFace: this.bodyFont(fonts), color: this.hex(palette.text),
          valign: 'top', lineSpacingMultiple: 1.4,
        });
      }
    }

    this.addFooter(slide, plan.index + 1, fonts, palette, theme);
  }

  // ──────────────────────────────────────────────
  //  CHART SLIDE — full-width chart
  // ──────────────────────────────────────────────

  private buildChart(
    slide: any, pptx: PptxGenJS, plan: ContentSlide, palette: ColorPalette,
    fonts: FontSpec[], contents: SlideContent[], theme: DefaultTheme,
  ) {
    slide.background = { color: this.hex(palette.background) };

    // Top accent
    slide.addShape('rect', { x: 0, y: 0, w: SW, h: 0.06, fill: { color: this.hex(palette.primary) } });

    // Title
    slide.addShape('rect', {
      x: MARGIN - 0.15, y: 0.5, w: 0.06, h: 0.6,
      fill: { color: this.hex(theme.decorSecondary) },
    });
    slide.addText(plan.title, {
      x: MARGIN + 0.1, y: 0.4, w: CONTENT_W - 0.1, h: 0.8,
      fontSize: 24, fontFace: this.titleFont(fonts), bold: true,
      color: this.hex(palette.primary), valign: 'middle',
    });
    contents.push({ type: 'text', placeholder: 'title', value: plan.title });

    const chartBlock = (plan.content_blocks || []).find(b => b.type === 'chart');
    const cY = 1.5;
    const cH = SH - cY - 1.0;

    // Light background panel behind chart
    slide.addShape('roundRect', {
      x: MARGIN - 0.1, y: cY - 0.1, w: CONTENT_W + 0.2, h: cH + 0.2,
      fill: { color: 'FFFFFF' }, rectRadius: 0.08,
      shadow: { type: 'outer', blur: 4, offset: 1, color: '000000', opacity: 0.06 },
    });

    if (chartBlock?.content?.data && Array.isArray(chartBlock.content.data)) {
      const chartData = chartBlock.content.data;
      const chartType = chartBlock.content.chartType || 'bar';
      const colors = palette.colors.map(c => c.replace('#', ''));

      try {
        const config: any = {
          x: MARGIN, y: cY, w: CONTENT_W, h: cH,
          showTitle: false,
          showLegend: true,
          legendPos: 'b',
          legendFontSize: 9,
          legendFontFace: this.bodyFont(fonts),
          catAxisLabelFontSize: 9,
          catAxisLabelFontFace: this.bodyFont(fonts),
          valAxisLabelFontSize: 9,
          catAxisOrientation: 'minMax',
          valAxisOrientation: 'minMax',
          chartColors: colors,
          valAxisNumFmt: '#,##0.0',
          catGridLine: { style: 'none' },
          valGridLine: { color: 'E8E8E8', style: 'dash', size: 0.5 },
        };

        const type = chartType === 'line' ? pptx.ChartType.line
          : chartType === 'pie' ? pptx.ChartType.pie
          : pptx.ChartType.bar;

        if (chartType === 'pie') config.showPercent = true;

        slide.addChart(type, chartData, config);
        contents.push({ type: 'chart' as any, placeholder: 'chart', value: chartBlock.content });
      } catch (err) {
        console.error('[SlideBuilder] Chart render error:', err);
        slide.addText(`[Chart: ${chartBlock.content.title || plan.title}]`, {
          x: MARGIN, y: cY, w: CONTENT_W, h: cH,
          fontSize: 14, fontFace: this.bodyFont(fonts), color: '999999',
          align: 'center', valign: 'middle',
        });
      }
    } else {
      // No chart data — fall back to content layout
      this.buildContent(slide, plan, palette, fonts, contents, theme);
      return;
    }

    // Source
    slide.addText('Source: Yahoo Finance, Company Reports', {
      x: MARGIN, y: SH - 0.65, w: CONTENT_W, h: 0.3,
      fontSize: 7, fontFace: this.bodyFont(fonts), color: '999999', italic: true,
    });

    this.addFooter(slide, plan.index + 1, fonts, palette, theme);
  }

  // ══════════════════════════════════════════════
  //  TEMPLATE MODE — all slide types
  // ══════════════════════════════════════════════

  private buildTemplateSlide(
    slide: any, plan: ContentSlide, palette: ColorPalette, fonts: FontSpec[],
    contents: SlideContent[], layout: SlideLayout | null, logo: string | null,
  ) {
    slide.background = { color: this.hex(layout?.background || palette.background) };

    const titlePh = this.ph(layout, 'title');
    const bodyPh = this.ph(layout, 'body');

    // Title
    const titleText = this.getBlockContent(plan, 'heading') || plan.title;
    this.addTextAt(slide, titleText, titlePh, { x: 0.8, y: 0.5, w: 11, h: 1.2 }, {
      fontSize: 28, fontFace: this.titleFont(fonts), bold: true,
      color: this.hex(palette.primary), valign: 'bottom',
    });
    contents.push({ type: 'text', placeholder: 'title', value: titleText });

    // Body content
    let yPos = (titlePh?.top ?? 0.5) + (titlePh?.height ?? 1.2) + 0.3;
    const cx = bodyPh?.left ?? 0.8;
    const cw = bodyPh?.width ?? (SW - 1.6);
    const maxY = SH - 0.5;

    for (const block of (plan.content_blocks || [])) {
      if (block.type === 'heading') continue;
      if (yPos > maxY - 0.5) break;

      if (block.type === 'bullet_list' && Array.isArray(block.content)) {
        const bullets = block.content.map((item: string) => ({
          text: item,
          options: {
            fontSize: bodyPh?.font?.size ?? 13,
            fontFace: bodyPh?.font?.name || this.bodyFont(fonts),
            color: this.hex(palette.text),
            bullet: { type: 'bullet' as const, char: '\u25B8', indent: 20 },
            paraSpaceBefore: 3, paraSpaceAfter: 8,
          },
        }));
        const h = Math.min(block.content.length * 0.45, maxY - yPos);
        slide.addText(bullets, { x: cx, y: yPos, w: cw, h, valign: 'top' });
        contents.push({ type: 'list', placeholder: 'body', value: block.content });
        yPos += h + 0.1;
      } else if (block.type === 'paragraph') {
        const text = String(block.content);
        const h = Math.min(Math.max(Math.ceil(text.length / 120) * 0.4, 0.5), maxY - yPos);
        slide.addText(text, {
          x: cx, y: yPos, w: cw, h,
          fontSize: bodyPh?.font?.size ?? 13,
          fontFace: bodyPh?.font?.name || this.bodyFont(fonts),
          color: this.hex(palette.text), valign: 'top', lineSpacingMultiple: 1.4,
        });
        contents.push({ type: 'text', placeholder: 'body', value: text });
        yPos += h + 0.15;
      }
    }

    // Logo on title slides
    if (plan.layout === 'Title Slide' && logo) {
      try {
        slide.addImage({
          data: logo, x: SW - 2.0, y: 0.3, w: 1.2, h: 1.2,
          sizing: { type: 'contain', w: 1.2, h: 1.2 },
        });
      } catch { /* skip */ }
    }
  }

  // ──────────────────────────────────────────────
  //  COMPANY LOGO FETCH
  // ──────────────────────────────────────────────

  private async fetchCompanyLogo(company?: string, ticker?: string): Promise<string | null> {
    if (!company && !ticker) return null;

    const domains: string[] = [];
    if (ticker) domains.push(`${ticker.toLowerCase()}.com`);
    if (company) {
      const clean = company.toLowerCase()
        .replace(/\s+(inc\.?|corp\.?|ltd\.?|llc|plc|co\.?|group|holdings?|international|enterprises?)$/i, '')
        .replace(/[^a-z0-9]/g, '');
      domains.push(`${clean}.com`);
    }

    for (const domain of domains) {
      try {
        const logoUrl = `https://logo.clearbit.com/${domain}?size=200`;
        const res = await fetch(logoUrl, { signal: AbortSignal.timeout(5000) });
        if (res.ok && res.headers.get('content-type')?.includes('image')) {
          const buffer = Buffer.from(await res.arrayBuffer());
          if (buffer.length > 500) {
            console.log(`[Logo] Found logo for ${domain} (${(buffer.length / 1024).toFixed(0)}KB)`);
            return `data:image/png;base64,${buffer.toString('base64')}`;
          }
        }
      } catch {
        // Try next domain
      }
    }

    console.log(`[Logo] No logo found for ${company || ticker}`);
    return null;
  }

  // ──────────────────────────────────────────────
  //  SHARED HELPERS
  // ──────────────────────────────────────────────

  private addFooter(
    slide: any, slideNum: number, fonts: FontSpec[],
    palette: ColorPalette, theme: DefaultTheme,
  ) {
    // Subtle bottom bar
    slide.addShape('rect', {
      x: 0, y: SH - 0.35, w: SW, h: 0.35,
      fill: { color: this.hex(theme.panelTint) },
    });
    slide.addText('CONFIDENTIAL', {
      x: MARGIN, y: SH - 0.32, w: 3, h: 0.25,
      fontSize: 7, fontFace: this.bodyFont(fonts), color: 'AAAAAA', italic: true,
    });
    slide.addText(String(slideNum), {
      x: SW - MARGIN - 0.6, y: SH - 0.32, w: 0.6, h: 0.25,
      fontSize: 8, fontFace: this.bodyFont(fonts), color: 'AAAAAA', align: 'right',
    });
  }

  private addTextAt(
    slide: any, text: string, ph: Placeholder | null,
    fallback: { x: number; y: number; w: number; h: number },
    style: any,
  ) {
    slide.addText(text, {
      x: ph?.left ?? fallback.x,
      y: ph?.top ?? fallback.y,
      w: ph?.width ?? fallback.w,
      h: ph?.height ?? fallback.h,
      fontSize: ph?.font?.size ?? style.fontSize,
      fontFace: ph?.font?.name || style.fontFace,
      bold: ph?.font?.bold ?? style.bold,
      color: ph?.font?.color ? this.hex(ph.font.color) : style.color,
      align: style.align,
      valign: style.valign,
    });
  }

  private findLayout(name: string, ta: TemplateAnalysis): SlideLayout | null {
    const exact = ta.slide_layouts.find(l => l.name === name);
    if (exact) return exact;
    const lower = name.toLowerCase();
    return ta.slide_layouts.find(l => {
      const ll = l.name.toLowerCase();
      return ll.includes(lower) || lower.includes(ll);
    }) || null;
  }

  private ph(layout: SlideLayout | null, type: Placeholder['type']): Placeholder | null {
    return layout?.placeholders.find(p => p.type === type) || null;
  }

  private masterName(layoutName: string): string {
    return `MASTER_${layoutName.replace(/\s+/g, '_')}`;
  }

  private addNotes(slide: any, plan: ContentSlide) {
    if (plan.talking_points?.length) {
      slide.addNotes(plan.talking_points.join('\n'));
    }
  }

  private hex(c: string | undefined): string { return (c || '333333').replace('#', ''); }
  private titleFont(f: FontSpec[]): string { return f[0]?.name || 'Calibri'; }
  private bodyFont(f: FontSpec[]): string { return f[2]?.name || f[0]?.name || 'Calibri'; }

  private getBlockContent(plan: ContentSlide, type: string): string | null {
    const b = (plan.content_blocks || []).find(b => b.type === type);
    return b ? String(b.content) : null;
  }
  private getAllBlockContent(plan: ContentSlide, type: string): string[] {
    return (plan.content_blocks || []).filter(b => b.type === type).map(b => String(b.content));
  }
}

export const slideBuilder = new SlideBuilderService();
